// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rlgam
double rlgam(double shape);
RcppExport SEXP _ozib_rlgam(SEXP shapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    rcpp_result_gen = Rcpp::wrap(rlgam(shape));
    return rcpp_result_gen;
END_RCPP
}
// beta_bart
List beta_bart(arma::mat& X, arma::vec& Y, arma::uvec& delta1, arma::uvec& delta0, arma::vec& yb, arma::mat& X_test, List hypers_, List opts_);
RcppExport SEXP _ozib_beta_bart(SEXP XSEXP, SEXP YSEXP, SEXP delta1SEXP, SEXP delta0SEXP, SEXP ybSEXP, SEXP X_testSEXP, SEXP hypers_SEXP, SEXP opts_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type delta1(delta1SEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type delta0(delta0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type yb(ybSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X_test(X_testSEXP);
    Rcpp::traits::input_parameter< List >::type hypers_(hypers_SEXP);
    Rcpp::traits::input_parameter< List >::type opts_(opts_SEXP);
    rcpp_result_gen = Rcpp::wrap(beta_bart(X, Y, delta1, delta0, yb, X_test, hypers_, opts_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ozib_rlgam", (DL_FUNC) &_ozib_rlgam, 1},
    {"_ozib_beta_bart", (DL_FUNC) &_ozib_beta_bart, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_ozib(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
