# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rlgam <- function(shape) {
    .Call(`_ozib_rlgam`, shape)
}

beta_bart <- function(X, Y, delta1, delta0, yb, X_test, hypers_, opts_) {
    .Call(`_ozib_beta_bart`, X, Y, delta1, delta0, yb, X_test, hypers_, opts_)
}

